'use client';
import {useState} from 'react';
type A={id:string;sectionId:string;title:string;slug:string;description:string;link:string|null};type S={slug:string;name:string;agendas:A[]};
export default function AgendaManager({sections}:{sections:S[]}){const [items,setItems]=useState(sections.flatMap(s=>s.agendas.map(a=>({...a,sectionSlug:s.slug} as A&{sectionSlug:string}))));const [form,setForm]=useState({sectionSlug:sections[0]?.slug||'umum',title:'',slug:'',description:'',link:''});const [msg,setMsg]=useState('');
 async function create(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/agendas',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...form,link:form.link||null})});const a=await r.json();if(!r.ok){setMsg(a.error);return}setItems([...items,{...a,sectionSlug:form.sectionSlug}]);setForm({...form,title:'',slug:'',description:'',link:''});setMsg('Agenda dibuat.')}
 async function edit(a:A&{sectionSlug:string}){const title=prompt('Judul agenda:',a.title);if(!title)return;const description=prompt('Deskripsi agenda:',a.description);if(description===null)return;const link=prompt('Link QR (kosongkan untuk menghapus):',a.link||'');const r=await fetch('/api/agendas/'+a.id,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({title,slug:a.slug,description,link:link||null})});if(r.ok){const updated=await r.json();setItems(items.map(x=>x.id===a.id?{...x,...updated}:x));setMsg('Agenda diperbarui.')}else setMsg('Gagal memperbarui agenda.')}
 async function remove(id:string){if(!confirm('Hapus agenda ini?'))return;const r=await fetch('/api/agendas/'+id,{method:'DELETE'});if(r.ok){setItems(items.filter(a=>a.id!==id));setMsg('Agenda dihapus.')}}
 return <section className="rounded-xl border border-black bg-white p-6"><h2 className="mb-5 text-2xl font-medium">Kelola Agenda</h2><form onSubmit={create} className="grid gap-3 md:grid-cols-5"><select className={input} value={form.sectionSlug} onChange={e=>setForm({...form,sectionSlug:e.target.value})}>{sections.map(s=><option key={s.slug}>{s.slug}</option>)}</select><input className={input} placeholder="Judul" required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input className={input} placeholder="Slug (opsional)" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/><input className={input} placeholder="Link QR (opsional)" type="url" value={form.link} onChange={e=>setForm({...form,link:e.target.value})}/><button className="rounded-lg bg-green-500 px-4 py-2 text-white">Tambah</button><textarea className={input+' md:col-span-4'} placeholder="Deskripsi" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></form><div className="mt-5 grid gap-3 sm:grid-cols-2">{items.map(a=><div key={a.id} className="rounded-lg border p-4"><b>{a.title}</b><p className="text-xs text-slate-500">{a.sectionSlug}/{a.slug}</p><p className="mt-1 text-sm text-slate-600">{a.description}</p> <div className="mt-3 flex gap-4 text-sm"><button onClick={()=>edit(a)} className="text-sky-700">Edit</button><button onClick={()=>remove(a.id)} className="text-red-600">Hapus</button></div></div>)}</div>{msg&&<p className="mt-3 text-sm text-slate-600">{msg}</p>}</section>}
const input='rounded-lg border border-black px-3 py-2 text-sm';
